### ISSUE TITLE
Support for nextjs 13.4 Turbopack

### ISSUE THREAD

**Issue by erwanriou** [aralroca/next-translate-plugin#20]

**Comment by edwinveldhuizen** [comment]
@aralroca looks like they currently do right? :)  https://turbo.build/pack/docs/features/customizing-turbopack

**Comment by aralroca** [comment]
great news @edwinveldhuizen !

**Comment by vhpx** [comment]
Any new updates regarding this issue?

**Comment by tomaszzmudzinski** [comment]
@aralroca more and more projects works without any issues with turbo. Maybe it's good time to make next-translate work with turbo? 😃

**Comment by tomaszzmudzinski** [comment]
Any new updates? 👀

**Comment by aralroca** [comment]
It is planned for version 3.0 which will be the next version.

**Comment by pnogier** [comment]
Hi guys, any update on this ? 👀

**Comment by moioo91120** [comment]
Hi, same question ! any date or timeline for version 3.0 ?

**Comment by poeck** [comment]
I managed to get it working by first adding this to my next.config.(js/ts):

´´´
  experimental: {
    turbo: {
      resolveAlias: {
        "@next-translate-root/": "./",
      },
      rules: {
        "./pages/**/*.tsx": {
          loaders: [
            {
              loader: require.resolve("next-translate-plugin/loader"),
              options: {
                basePath: __dirname,
                pagesFolder: "pages",
                appFolder: "app",
                hasAppJs: true,
                hasGetInitialPropsOnAppJs: false,
                extensionsRgx: "/\.(tsx|ts|js|mjs|jsx)$/",
                revalidate: 0,
                existLocalesFolder: true,
              },
            },
          ],
        },
      },
    },
  },
´´´

For now I hardcoded all the `options` to work for my project, but those won't be the same in most other projects - so make sure to change them if it doesn't work out of the box.

I am also using a monorepo which has the locales in the root folder while the project is inside `apps/web` and I also had to create a symlink for the locales folder to `apps/web`. This might not be necessary if you already have your locales inside the project directory.

Hope this helps!

**Comment by DonovanCharpin** [comment]
@poeck Did you make it work with turbo in next 15?

On my side, the dev server starts but I get an error when loading a page.

```
Error evaluating Node.js code
Error: Cannot find module 'file:///<PATH_TO_REPO>/node_modules/next-translate-plugin/loader'
```

Here is my next.config.mjs

``` javascript
turbo: {
  resolveAlias: {
    "@next-translate-root/": "./",
  },
  rules: {
    "./pages/**/*.js": {
      loaders: [
        {
          loader: import.meta.resolve('next-translate-plugin/loader'),
          options: {
            basePath: path.resolve(),
            pagesFolder: "pages",
            appFolder: "app",
            hasAppJs: false,
            hasGetInitialPropsOnAppJs: true,
            extensionsRgx: "/\.(tsx|ts|js|mjs|jsx)$/",
            revalidate: 0,
            existLocalesFolder: true,
          },
        },
      ],
    },
 },
},
```

**Comment by poeck** [comment]
@DonovanCharpin Yes, I got it to work in Next 15.2.4.

I'm pretty sure the error is happening because you're using import.meta.resolve instead of require.resolve, which seems to behave differently somehow. For me, `require.resolve("next-translate-plugin/loader")` resolves to this path:

`<path-to-root-of-project>/node_modules/next-translate-plugin/lib/cjs/loader.js`.

Note that it also does not have a file:// protocol at the beginning.

Not sure if you already tried using `require.resolve`, but if you could use it, it might work for you as well.

Alternatively, I would just try to hardcode the path to the loader.js file from next-translate-plugin inside `node_modules` - not a very nice solution, but it should fix this.

**Comment by DonovanCharpin** [comment]
@poeck You are right! The require.resolve is a bit smarter because it read in the package to resolve the linked file!

I replaced it with this, and it works. Thanks!

``` javascript
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);

{
  ...
  loader: require.resolve("next-translate-plugin/loader"),
  ...
}

```

**Comment by p-schlickmann** [comment]
On Next.js 15.4.5, using App Router, I was able to make it work with:

```javascript
import i18nConfig from "../../../i18n.js";
import loadNamespaces from "next-translate/loadNamespaces";

const dangerouslyMockNextTranslateOnDevelopmentEnvironment = async (props) => {
  // This is a hacky patch meant for development only, in our case we depend 
  // on turbopack to make the development experience somewhat doable.

  const params = await props.params;
  const searchParams = await props.searchParams;
  const detectedLang = params?.lang ?? searchParams?.lang;

  const config = {
    ...i18nConfig,
    __i18nConfig: "__i18nConfig",
    locale: detectedLang ?? "en",
    loaderName: "custom-loader",
    pathname: "/",
  };

  const { __namespaces, __lang } = await loadNamespaces({
    ...config,
    loadLocaleFrom: (lang, ns) => {
      // make sure to specify the correct path for your project
      return import(`../../../locales/${lang}/${ns}.json`).then(
        (m) => m.default,
      );
    },
  });

  globalThis.__NEXT_TRANSLATE__ = {
    lang: __lang,
    namespaces: __namespaces,
    config,
  };
};

const Page = async (props) => {
  if (
    process.env.NODE_ENV === "development" &&
    process.env.NEXT_PUBLIC_MOCK_TRANSLATE === "true"
  ) {
    await dangerouslyMockNextTranslateOnDevelopmentEnvironment(props);
  }

 // ... rest of your App Router page
}
```
